### PR TITLE
Better error message

### PR DESCRIPTION
**Pull request by Kucharssim**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1401

I actually don't know what causes this error, so we can't be much more specific than that, I am afraid. Do you have any other idea how to improve this situation, @AlexanderLyNL ?

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
What goes wrong here is that we're dealing with an overflow problem, so nothing can really be done about it other than developing non-parametric methods for this.

**Comment by Kucharssim** [comment]
Right. Do you agree with the change of the error message then? Or should I change it somewhat?

**Comment by AlexanderLyNL** [comment]
I thought cannot compute was quite clear, but your suggestion works as well. Perhaps a small adaptation. 

Some of Bayes factors in the sequence could not be computed, likely caused by some extreme features of the data, such as a large number of observations and observed correlation.

**Comment by AlexanderLyNL** [comment]
I can't spell:

Some of the Bayes factors in the sequence could not be computed, likely caused by an extreme feature of the data, such as a large number of observations and observed correlation.

**Comment by AlexanderLyNL** [comment]
Very nice, thanks!

**Pull request merged**
